CC=gcc
CFLAGS=-c -Wall

all: shell

shell: commands.o jobs.o parser.o shell.o
	$(CC) commands.o jobs.o parser.o shell.o -o shell

commands.o: commands.c commands.h job.h parser.h
	$(CC) $(CFLAGS) commands.c

jobs.o: jobs.c commands.h job.h parser.h
	$(CC) $(CFLAGS) jobs.c

parser.o: parser.c job.h parser.h
	$(CC) $(CFLAGS) parser.c

shell.o: shell.c commands.h job.h parser.h shell.h
	$(CC) $(CFLAGS) shell.c

clean:
	rm -rf *o shell
